//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilitiesDeviceERP.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sap.com/xi/IS-U/Global2", ConfigurationName="ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out")]
    public interface UtilitiesDeviceERPSmartMeterCreateRequest_Out {
        
        // CODEGEN: Generating message contract since the operation UtilitiesDeviceERPSmartMeterCreateRequest_Out is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void UtilitiesDeviceERPSmartMeterCreateRequest_Out(UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        System.Threading.Tasks.Task UtilitiesDeviceERPSmartMeterCreateRequest_OutAsync(UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilsDvceERPSmrtMtrCrteReqMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BusinessDocumentMessageHeader messageHeaderField;
        
        private UtilsDvceERPSmrtMtrCrteReqUtilsDvce utilitiesDeviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessDocumentMessageHeader MessageHeader {
            get {
                return this.messageHeaderField;
            }
            set {
                this.messageHeaderField = value;
                this.RaisePropertyChanged("MessageHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UtilsDvceERPSmrtMtrCrteReqUtilsDvce UtilitiesDevice {
            get {
                return this.utilitiesDeviceField;
            }
            set {
                this.utilitiesDeviceField = value;
                this.RaisePropertyChanged("UtilitiesDevice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessDocumentMessageHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BusinessDocumentMessageID idField;
        
        private UUID uUIDField;
        
        private BusinessDocumentMessageID referenceIDField;
        
        private UUID referenceUUIDField;
        
        private System.DateTime creationDateTimeField;
        
        private bool testDataIndicatorField;
        
        private bool testDataIndicatorFieldSpecified;
        
        private bool reconciliationIndicatorField;
        
        private bool reconciliationIndicatorFieldSpecified;
        
        private string senderBusinessSystemIDField;
        
        private string recipientBusinessSystemIDField;
        
        private BusinessDocumentMessageHeaderParty senderPartyField;
        
        private BusinessDocumentMessageHeaderParty[] recipientPartyField;
        
        private BusinessScope[] businessScopeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessDocumentMessageID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public UUID UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BusinessDocumentMessageID ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("ReferenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public UUID ReferenceUUID {
            get {
                return this.referenceUUIDField;
            }
            set {
                this.referenceUUIDField = value;
                this.RaisePropertyChanged("ReferenceUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime CreationDateTime {
            get {
                return this.creationDateTimeField;
            }
            set {
                this.creationDateTimeField = value;
                this.RaisePropertyChanged("CreationDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool TestDataIndicator {
            get {
                return this.testDataIndicatorField;
            }
            set {
                this.testDataIndicatorField = value;
                this.RaisePropertyChanged("TestDataIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestDataIndicatorSpecified {
            get {
                return this.testDataIndicatorFieldSpecified;
            }
            set {
                this.testDataIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("TestDataIndicatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool ReconciliationIndicator {
            get {
                return this.reconciliationIndicatorField;
            }
            set {
                this.reconciliationIndicatorField = value;
                this.RaisePropertyChanged("ReconciliationIndicator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReconciliationIndicatorSpecified {
            get {
                return this.reconciliationIndicatorFieldSpecified;
            }
            set {
                this.reconciliationIndicatorFieldSpecified = value;
                this.RaisePropertyChanged("ReconciliationIndicatorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=7)]
        public string SenderBusinessSystemID {
            get {
                return this.senderBusinessSystemIDField;
            }
            set {
                this.senderBusinessSystemIDField = value;
                this.RaisePropertyChanged("SenderBusinessSystemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=8)]
        public string RecipientBusinessSystemID {
            get {
                return this.recipientBusinessSystemIDField;
            }
            set {
                this.recipientBusinessSystemIDField = value;
                this.RaisePropertyChanged("RecipientBusinessSystemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public BusinessDocumentMessageHeaderParty SenderParty {
            get {
                return this.senderPartyField;
            }
            set {
                this.senderPartyField = value;
                this.RaisePropertyChanged("SenderParty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecipientParty", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public BusinessDocumentMessageHeaderParty[] RecipientParty {
            get {
                return this.recipientPartyField;
            }
            set {
                this.recipientPartyField = value;
                this.RaisePropertyChanged("RecipientParty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessScope", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public BusinessScope[] BusinessScope {
            get {
                return this.businessScopeField;
            }
            set {
                this.businessScopeField = value;
                this.RaisePropertyChanged("BusinessScope");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessDocumentMessageID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string schemeAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencySchemeAgencyID {
            get {
                return this.schemeAgencySchemeAgencyIDField;
            }
            set {
                this.schemeAgencySchemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencySchemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilitiesAdvancedMeteringSystemID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilsDvceERPSmrtMtrCrteReqSmrtMtr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UtilitiesAdvancedMeteringSystemID utilitiesAdvancedMeteringSystemIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UtilitiesAdvancedMeteringSystemID UtilitiesAdvancedMeteringSystemID {
            get {
                return this.utilitiesAdvancedMeteringSystemIDField;
            }
            set {
                this.utilitiesAdvancedMeteringSystemIDField = value;
                this.RaisePropertyChanged("UtilitiesAdvancedMeteringSystemID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilsDvceERPSmrtMtrCrteReqIndivMatlMfrInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PartyInternalID partyInternalIDField;
        
        private ProductInternalID partNumberIDField;
        
        private string serialIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PartyInternalID PartyInternalID {
            get {
                return this.partyInternalIDField;
            }
            set {
                this.partyInternalIDField = value;
                this.RaisePropertyChanged("PartyInternalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ProductInternalID PartNumberID {
            get {
                return this.partNumberIDField;
            }
            set {
                this.partNumberIDField = value;
                this.RaisePropertyChanged("PartNumberID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string SerialID {
            get {
                return this.serialIDField;
            }
            set {
                this.serialIDField = value;
                this.RaisePropertyChanged("SerialID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class PartyInternalID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class ProductInternalID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class ProductStandardID_V1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilitiesDeviceID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilsDvceERPSmrtMtrCrteReqUtilsDvce : object, System.ComponentModel.INotifyPropertyChanged {
        
        private UtilitiesDeviceID idField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string serialIDField;
        
        private ProductInternalID materialIDField;
        
        private ProductStandardID_V1 productUniqueItemIDField;
        
        private UtilsDvceERPSmrtMtrCrteReqIndivMatlMfrInfo individualMaterialManufacturerInformationField;
        
        private UtilsDvceERPSmrtMtrCrteReqSmrtMtr smartMeterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UtilitiesDeviceID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string SerialID {
            get {
                return this.serialIDField;
            }
            set {
                this.serialIDField = value;
                this.RaisePropertyChanged("SerialID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ProductInternalID MaterialID {
            get {
                return this.materialIDField;
            }
            set {
                this.materialIDField = value;
                this.RaisePropertyChanged("MaterialID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ProductStandardID_V1 ProductUniqueItemID {
            get {
                return this.productUniqueItemIDField;
            }
            set {
                this.productUniqueItemIDField = value;
                this.RaisePropertyChanged("ProductUniqueItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public UtilsDvceERPSmrtMtrCrteReqIndivMatlMfrInfo IndividualMaterialManufacturerInformation {
            get {
                return this.individualMaterialManufacturerInformationField;
            }
            set {
                this.individualMaterialManufacturerInformationField = value;
                this.RaisePropertyChanged("IndividualMaterialManufacturerInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public UtilsDvceERPSmrtMtrCrteReqSmrtMtr SmartMeter {
            get {
                return this.smartMeterField;
            }
            set {
                this.smartMeterField = value;
                this.RaisePropertyChanged("SmartMeter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessScopeID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessScopeInstanceID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessScopeTypeCode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string listIDField;
        
        private string listVersionIDField;
        
        private string listAgencyIDField;
        
        private string listAgencySchemeIDField;
        
        private string listAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listID {
            get {
                return this.listIDField;
            }
            set {
                this.listIDField = value;
                this.RaisePropertyChanged("listID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listVersionID {
            get {
                return this.listVersionIDField;
            }
            set {
                this.listVersionIDField = value;
                this.RaisePropertyChanged("listVersionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID {
            get {
                return this.listAgencyIDField;
            }
            set {
                this.listAgencyIDField = value;
                this.RaisePropertyChanged("listAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeID {
            get {
                return this.listAgencySchemeIDField;
            }
            set {
                this.listAgencySchemeIDField = value;
                this.RaisePropertyChanged("listAgencySchemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeAgencyID {
            get {
                return this.listAgencySchemeAgencyIDField;
            }
            set {
                this.listAgencySchemeAgencyIDField = value;
                this.RaisePropertyChanged("listAgencySchemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessScope : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BusinessScopeTypeCode typeCodeField;
        
        private BusinessScopeInstanceID instanceIDField;
        
        private BusinessScopeID idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BusinessScopeTypeCode TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public BusinessScopeInstanceID InstanceID {
            get {
                return this.instanceIDField;
            }
            set {
                this.instanceIDField = value;
                this.RaisePropertyChanged("InstanceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BusinessScopeID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class EmailURI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class MEDIUM_Name : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string languageCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
                this.RaisePropertyChanged("languageCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class PhoneNumber : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaIDField;
        
        private string subscriberIDField;
        
        private string extensionIDField;
        
        private string countryCodeField;
        
        private string countryDiallingCodeField;
        
        private MEDIUM_Name countryNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=0)]
        public string AreaID {
            get {
                return this.areaIDField;
            }
            set {
                this.areaIDField = value;
                this.RaisePropertyChanged("AreaID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
                this.RaisePropertyChanged("SubscriberID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=2)]
        public string ExtensionID {
            get {
                return this.extensionIDField;
            }
            set {
                this.extensionIDField = value;
                this.RaisePropertyChanged("ExtensionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=3)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=4)]
        public string CountryDiallingCode {
            get {
                return this.countryDiallingCodeField;
            }
            set {
                this.countryDiallingCodeField = value;
                this.RaisePropertyChanged("CountryDiallingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public MEDIUM_Name CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
                this.RaisePropertyChanged("CountryName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class ContactPersonInternalID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessDocumentMessageHeaderPartyContactPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ContactPersonInternalID internalIDField;
        
        private string[] organisationFormattedNameField;
        
        private string[] personFormattedNameField;
        
        private PhoneNumber[] phoneNumberField;
        
        private PhoneNumber[] faxNumberField;
        
        private EmailURI[] emailURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ContactPersonInternalID InternalID {
            get {
                return this.internalIDField;
            }
            set {
                this.internalIDField = value;
                this.RaisePropertyChanged("InternalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrganisationFormattedName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] OrganisationFormattedName {
            get {
                return this.organisationFormattedNameField;
            }
            set {
                this.organisationFormattedNameField = value;
                this.RaisePropertyChanged("OrganisationFormattedName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonFormattedName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string[] PersonFormattedName {
            get {
                return this.personFormattedNameField;
            }
            set {
                this.personFormattedNameField = value;
                this.RaisePropertyChanged("PersonFormattedName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhoneNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public PhoneNumber[] PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FaxNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public PhoneNumber[] FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
                this.RaisePropertyChanged("FaxNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmailURI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public EmailURI[] EmailURI {
            get {
                return this.emailURIField;
            }
            set {
                this.emailURIField = value;
                this.RaisePropertyChanged("EmailURI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class PartyStandardID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessDocumentMessageHeaderParty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PartyInternalID internalIDField;
        
        private PartyStandardID[] standardIDField;
        
        private BusinessDocumentMessageHeaderPartyContactPerson contactPersonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public PartyInternalID InternalID {
            get {
                return this.internalIDField;
            }
            set {
                this.internalIDField = value;
                this.RaisePropertyChanged("InternalID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StandardID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PartyStandardID[] StandardID {
            get {
                return this.standardIDField;
            }
            set {
                this.standardIDField = value;
                this.RaisePropertyChanged("StandardID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public BusinessDocumentMessageHeaderPartyContactPerson ContactPerson {
            get {
                return this.contactPersonField;
            }
            set {
                this.contactPersonField = value;
                this.RaisePropertyChanged("ContactPerson");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UUID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
                this.RaisePropertyChanged("schemeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
                this.RaisePropertyChanged("schemeAgencyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UtilitiesDeviceERPSmartMeterCreateRequest_Out1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global", Order=0)]
        public UtilitiesDeviceERP.ServiceReference2.UtilsDvceERPSmrtMtrCrteReqMsg UtilitiesDeviceERPSmartMeterCreateRequest;
        
        public UtilitiesDeviceERPSmartMeterCreateRequest_Out1() {
        }
        
        public UtilitiesDeviceERPSmartMeterCreateRequest_Out1(UtilitiesDeviceERP.ServiceReference2.UtilsDvceERPSmrtMtrCrteReqMsg UtilitiesDeviceERPSmartMeterCreateRequest) {
            this.UtilitiesDeviceERPSmartMeterCreateRequest = UtilitiesDeviceERPSmartMeterCreateRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UtilitiesDeviceERPSmartMeterCreateRequest_OutChannel : UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilitiesDeviceERPSmartMeterCreateRequest_OutClient : System.ServiceModel.ClientBase<UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out>, UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out {
        
        public UtilitiesDeviceERPSmartMeterCreateRequest_OutClient() {
        }
        
        public UtilitiesDeviceERPSmartMeterCreateRequest_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilitiesDeviceERPSmartMeterCreateRequest_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitiesDeviceERPSmartMeterCreateRequest_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitiesDeviceERPSmartMeterCreateRequest_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out.UtilitiesDeviceERPSmartMeterCreateRequest_Out(UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out1 request) {
            base.Channel.UtilitiesDeviceERPSmartMeterCreateRequest_Out(request);
        }
        
        public void UtilitiesDeviceERPSmartMeterCreateRequest_Out(UtilitiesDeviceERP.ServiceReference2.UtilsDvceERPSmrtMtrCrteReqMsg UtilitiesDeviceERPSmartMeterCreateRequest) {
            UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out1 inValue = new UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out1();
            inValue.UtilitiesDeviceERPSmartMeterCreateRequest = UtilitiesDeviceERPSmartMeterCreateRequest;
            ((UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out)(this)).UtilitiesDeviceERPSmartMeterCreateRequest_Out(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out.UtilitiesDeviceERPSmartMeterCreateRequest_OutAsync(UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out1 request) {
            return base.Channel.UtilitiesDeviceERPSmartMeterCreateRequest_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task UtilitiesDeviceERPSmartMeterCreateRequest_OutAsync(UtilitiesDeviceERP.ServiceReference2.UtilsDvceERPSmrtMtrCrteReqMsg UtilitiesDeviceERPSmartMeterCreateRequest) {
            UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out1 inValue = new UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out1();
            inValue.UtilitiesDeviceERPSmartMeterCreateRequest = UtilitiesDeviceERPSmartMeterCreateRequest;
            return ((UtilitiesDeviceERP.ServiceReference2.UtilitiesDeviceERPSmartMeterCreateRequest_Out)(this)).UtilitiesDeviceERPSmartMeterCreateRequest_OutAsync(inValue);
        }
    }
}
