//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UtilitiesDeviceERP.abc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UtilitiesDeviceERPSmartMeterCreateRequest_OutBinding", Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilitiesDeviceERPSmartMeterCreateRequest_OutBinding : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UtilitiesDeviceERPSmartMeterCreateRequest_OutOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UtilitiesDeviceERPSmartMeterCreateRequest_OutBinding() {
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UtilitiesDeviceERPSmartMeterCreateRequest_OutCompletedEventHandler UtilitiesDeviceERPSmartMeterCreateRequest_OutCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void UtilitiesDeviceERPSmartMeterCreateRequest_Out([System.Xml.Serialization.XmlElementAttribute(Namespace="http://sap.com/xi/SAPGlobal20/Global")] UtilsDvceERPSmrtMtrCrteReqMsg UtilitiesDeviceERPSmartMeterCreateRequest) {
            this.Invoke("UtilitiesDeviceERPSmartMeterCreateRequest_Out", new object[] {
                        UtilitiesDeviceERPSmartMeterCreateRequest});
        }
        
        /// <remarks/>
        public void UtilitiesDeviceERPSmartMeterCreateRequest_OutAsync(UtilsDvceERPSmrtMtrCrteReqMsg UtilitiesDeviceERPSmartMeterCreateRequest) {
            this.UtilitiesDeviceERPSmartMeterCreateRequest_OutAsync(UtilitiesDeviceERPSmartMeterCreateRequest, null);
        }
        
        /// <remarks/>
        public void UtilitiesDeviceERPSmartMeterCreateRequest_OutAsync(UtilsDvceERPSmrtMtrCrteReqMsg UtilitiesDeviceERPSmartMeterCreateRequest, object userState) {
            if ((this.UtilitiesDeviceERPSmartMeterCreateRequest_OutOperationCompleted == null)) {
                this.UtilitiesDeviceERPSmartMeterCreateRequest_OutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUtilitiesDeviceERPSmartMeterCreateRequest_OutOperationCompleted);
            }
            this.InvokeAsync("UtilitiesDeviceERPSmartMeterCreateRequest_Out", new object[] {
                        UtilitiesDeviceERPSmartMeterCreateRequest}, this.UtilitiesDeviceERPSmartMeterCreateRequest_OutOperationCompleted, userState);
        }
        
        private void OnUtilitiesDeviceERPSmartMeterCreateRequest_OutOperationCompleted(object arg) {
            if ((this.UtilitiesDeviceERPSmartMeterCreateRequest_OutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UtilitiesDeviceERPSmartMeterCreateRequest_OutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilsDvceERPSmrtMtrCrteReqMsg {
        
        private BusinessDocumentMessageHeader messageHeaderField;
        
        private UtilsDvceERPSmrtMtrCrteReqUtilsDvce utilitiesDeviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessDocumentMessageHeader MessageHeader {
            get {
                return this.messageHeaderField;
            }
            set {
                this.messageHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UtilsDvceERPSmrtMtrCrteReqUtilsDvce UtilitiesDevice {
            get {
                return this.utilitiesDeviceField;
            }
            set {
                this.utilitiesDeviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessDocumentMessageHeader {
        
        private BusinessDocumentMessageID idField;
        
        private UUID uUIDField;
        
        private BusinessDocumentMessageID referenceIDField;
        
        private UUID referenceUUIDField;
        
        private System.DateTime creationDateTimeField;
        
        private bool testDataIndicatorField;
        
        private bool testDataIndicatorFieldSpecified;
        
        private bool reconciliationIndicatorField;
        
        private bool reconciliationIndicatorFieldSpecified;
        
        private string senderBusinessSystemIDField;
        
        private string recipientBusinessSystemIDField;
        
        private BusinessDocumentMessageHeaderParty senderPartyField;
        
        private BusinessDocumentMessageHeaderParty[] recipientPartyField;
        
        private BusinessScope[] businessScopeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessDocumentMessageID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UUID UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessDocumentMessageID ReferenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UUID ReferenceUUID {
            get {
                return this.referenceUUIDField;
            }
            set {
                this.referenceUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime CreationDateTime {
            get {
                return this.creationDateTimeField;
            }
            set {
                this.creationDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool TestDataIndicator {
            get {
                return this.testDataIndicatorField;
            }
            set {
                this.testDataIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TestDataIndicatorSpecified {
            get {
                return this.testDataIndicatorFieldSpecified;
            }
            set {
                this.testDataIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ReconciliationIndicator {
            get {
                return this.reconciliationIndicatorField;
            }
            set {
                this.reconciliationIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReconciliationIndicatorSpecified {
            get {
                return this.reconciliationIndicatorFieldSpecified;
            }
            set {
                this.reconciliationIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SenderBusinessSystemID {
            get {
                return this.senderBusinessSystemIDField;
            }
            set {
                this.senderBusinessSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string RecipientBusinessSystemID {
            get {
                return this.recipientBusinessSystemIDField;
            }
            set {
                this.recipientBusinessSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessDocumentMessageHeaderParty SenderParty {
            get {
                return this.senderPartyField;
            }
            set {
                this.senderPartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecipientParty", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessDocumentMessageHeaderParty[] RecipientParty {
            get {
                return this.recipientPartyField;
            }
            set {
                this.recipientPartyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessScope", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessScope[] BusinessScope {
            get {
                return this.businessScopeField;
            }
            set {
                this.businessScopeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessDocumentMessageID {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string schemeAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencySchemeAgencyID {
            get {
                return this.schemeAgencySchemeAgencyIDField;
            }
            set {
                this.schemeAgencySchemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilitiesAdvancedMeteringSystemID {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilsDvceERPSmrtMtrCrteReqSmrtMtr {
        
        private UtilitiesAdvancedMeteringSystemID utilitiesAdvancedMeteringSystemIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UtilitiesAdvancedMeteringSystemID UtilitiesAdvancedMeteringSystemID {
            get {
                return this.utilitiesAdvancedMeteringSystemIDField;
            }
            set {
                this.utilitiesAdvancedMeteringSystemIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilsDvceERPSmrtMtrCrteReqIndivMatlMfrInfo {
        
        private PartyInternalID partyInternalIDField;
        
        private ProductInternalID partNumberIDField;
        
        private string serialIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyInternalID PartyInternalID {
            get {
                return this.partyInternalIDField;
            }
            set {
                this.partyInternalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductInternalID PartNumberID {
            get {
                return this.partNumberIDField;
            }
            set {
                this.partNumberIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SerialID {
            get {
                return this.serialIDField;
            }
            set {
                this.serialIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class PartyInternalID {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class ProductInternalID {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class ProductStandardID_V1 {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilitiesDeviceID {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UtilsDvceERPSmrtMtrCrteReqUtilsDvce {
        
        private UtilitiesDeviceID idField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private string serialIDField;
        
        private ProductInternalID materialIDField;
        
        private ProductStandardID_V1 productUniqueItemIDField;
        
        private UtilsDvceERPSmrtMtrCrteReqIndivMatlMfrInfo individualMaterialManufacturerInformationField;
        
        private UtilsDvceERPSmrtMtrCrteReqSmrtMtr smartMeterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UtilitiesDeviceID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SerialID {
            get {
                return this.serialIDField;
            }
            set {
                this.serialIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductInternalID MaterialID {
            get {
                return this.materialIDField;
            }
            set {
                this.materialIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductStandardID_V1 ProductUniqueItemID {
            get {
                return this.productUniqueItemIDField;
            }
            set {
                this.productUniqueItemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UtilsDvceERPSmrtMtrCrteReqIndivMatlMfrInfo IndividualMaterialManufacturerInformation {
            get {
                return this.individualMaterialManufacturerInformationField;
            }
            set {
                this.individualMaterialManufacturerInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UtilsDvceERPSmrtMtrCrteReqSmrtMtr SmartMeter {
            get {
                return this.smartMeterField;
            }
            set {
                this.smartMeterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessScopeID {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessScopeInstanceID {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessScopeTypeCode {
        
        private string listIDField;
        
        private string listVersionIDField;
        
        private string listAgencyIDField;
        
        private string listAgencySchemeIDField;
        
        private string listAgencySchemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listID {
            get {
                return this.listIDField;
            }
            set {
                this.listIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listVersionID {
            get {
                return this.listVersionIDField;
            }
            set {
                this.listVersionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencyID {
            get {
                return this.listAgencyIDField;
            }
            set {
                this.listAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeID {
            get {
                return this.listAgencySchemeIDField;
            }
            set {
                this.listAgencySchemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string listAgencySchemeAgencyID {
            get {
                return this.listAgencySchemeAgencyIDField;
            }
            set {
                this.listAgencySchemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessScope {
        
        private BusinessScopeTypeCode typeCodeField;
        
        private BusinessScopeInstanceID instanceIDField;
        
        private BusinessScopeID idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessScopeTypeCode TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessScopeInstanceID InstanceID {
            get {
                return this.instanceIDField;
            }
            set {
                this.instanceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessScopeID ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class EmailURI {
        
        private string schemeIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class MEDIUM_Name {
        
        private string languageCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class PhoneNumber {
        
        private string areaIDField;
        
        private string subscriberIDField;
        
        private string extensionIDField;
        
        private string countryCodeField;
        
        private string countryDiallingCodeField;
        
        private MEDIUM_Name countryNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string AreaID {
            get {
                return this.areaIDField;
            }
            set {
                this.areaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string SubscriberID {
            get {
                return this.subscriberIDField;
            }
            set {
                this.subscriberIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string ExtensionID {
            get {
                return this.extensionIDField;
            }
            set {
                this.extensionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token")]
        public string CountryDiallingCode {
            get {
                return this.countryDiallingCodeField;
            }
            set {
                this.countryDiallingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MEDIUM_Name CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class ContactPersonInternalID {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessDocumentMessageHeaderPartyContactPerson {
        
        private ContactPersonInternalID internalIDField;
        
        private string[] organisationFormattedNameField;
        
        private string[] personFormattedNameField;
        
        private PhoneNumber[] phoneNumberField;
        
        private PhoneNumber[] faxNumberField;
        
        private EmailURI[] emailURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ContactPersonInternalID InternalID {
            get {
                return this.internalIDField;
            }
            set {
                this.internalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrganisationFormattedName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] OrganisationFormattedName {
            get {
                return this.organisationFormattedNameField;
            }
            set {
                this.organisationFormattedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonFormattedName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] PersonFormattedName {
            get {
                return this.personFormattedNameField;
            }
            set {
                this.personFormattedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhoneNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PhoneNumber[] PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FaxNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PhoneNumber[] FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmailURI", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EmailURI[] EmailURI {
            get {
                return this.emailURIField;
            }
            set {
                this.emailURIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class PartyStandardID {
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class BusinessDocumentMessageHeaderParty {
        
        private PartyInternalID internalIDField;
        
        private PartyStandardID[] standardIDField;
        
        private BusinessDocumentMessageHeaderPartyContactPerson contactPersonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyInternalID InternalID {
            get {
                return this.internalIDField;
            }
            set {
                this.internalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StandardID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PartyStandardID[] StandardID {
            get {
                return this.standardIDField;
            }
            set {
                this.standardIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BusinessDocumentMessageHeaderPartyContactPerson ContactPerson {
            get {
                return this.contactPersonField;
            }
            set {
                this.contactPersonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sap.com/xi/IS-U/Global2")]
    public partial class UUID {
        
        private string schemeIDField;
        
        private string schemeAgencyIDField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeID {
            get {
                return this.schemeIDField;
            }
            set {
                this.schemeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string schemeAgencyID {
            get {
                return this.schemeAgencyIDField;
            }
            set {
                this.schemeAgencyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="token")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UtilitiesDeviceERPSmartMeterCreateRequest_OutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591